import { useState, useEffect, useCallback } from "react";
import { Card, CardHeader, CardTitle, CardContent, CardDescription } from "../../components/ui/Card";
import { Table, TableHeader, TableBody, TableHead, TableRow, TableCell } from "../../components/ui/Table";
import { Button } from "../../components/ui/Button";
import { api } from "../../lib/api";
import { ShieldCheck, History, RefreshCw } from "lucide-react";

interface AuditLogItem {
  id: string;
  action: string;
  entity: string;
  entityId?: string;
  details?: string;
  userId?: string;
  userEmail?: string;
  ipAddress?: string;
  createdAt: string;
}

export function AuditLogs() {
  const [logs, setLogs] = useState<AuditLogItem[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [page, setPage] = useState(1);
  const [totalPages, setTotalPages] = useState(1);

  const fetchAuditLogs = useCallback(async (currentPage: number) => {
    setIsLoading(true);
    try {
      const response = await api.get(`/audit-logs?page=${currentPage}&limit=20`);
      if (response.data.success) {
        setLogs(response.data.data.logs);
        setTotalPages(response.data.data.pagination.totalPages || 1);
      }
    } catch (err) {
      console.error("Failed to fetch audit logs:", err);
      // Fallback empty feed
      setLogs([]);
    } finally {
      setIsLoading(false);
    }
  }, []);

  useEffect(() => {
    fetchAuditLogs(page);
  }, [fetchAuditLogs, page]);

  return (
    <div className="space-y-6 animate-in fade-in slide-in-from-bottom-4 duration-500">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-3xl font-bold tracking-tight text-secondary-900 dark:text-secondary-50">
            Audit Trail & Logs
          </h2>
          <p className="text-secondary-500 dark:text-secondary-400 mt-1">
            System-wide security activity feed and immutable change tracking for compliance.
          </p>
        </div>

        <Button variant="outline" onClick={() => fetchAuditLogs(page)} className="flex items-center">
          <RefreshCw className="mr-2 h-4 w-4" />
          Refresh Feed
        </Button>
      </div>

      <Card>
        <CardHeader>
          <CardTitle className="flex items-center">
            <ShieldCheck className="mr-2 h-5 w-5 text-primary-600 dark:text-primary-400" />
            Security & Activity Audit History
          </CardTitle>
          <CardDescription>
            Logs generated by tenant users, automated financial calculations, and compliance rules.
          </CardDescription>
        </CardHeader>
        <CardContent>
          {isLoading ? (
            <div className="py-8 text-center text-secondary-500">Loading audit records...</div>
          ) : logs.length === 0 ? (
            <div className="py-12 text-center text-secondary-500 text-sm">
              <History className="mx-auto h-8 w-8 text-secondary-400 mb-2" />
              No audit logs recorded yet. Create an account or post a journal entry to populate the activity feed.
            </div>
          ) : (
            <>
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Timestamp</TableHead>
                    <TableHead>Action</TableHead>
                    <TableHead>Entity</TableHead>
                    <TableHead>User / Executor</TableHead>
                    <TableHead>Details</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {logs.map((log) => (
                    <TableRow key={log.id}>
                      <TableCell className="text-xs text-secondary-500 whitespace-nowrap">
                        {new Date(log.createdAt).toLocaleString()}
                      </TableCell>
                      <TableCell>
                        <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-semibold bg-primary-50 text-primary-700 dark:bg-primary-900/40 dark:text-primary-300">
                          {log.action}
                        </span>
                      </TableCell>
                      <TableCell className="font-medium text-secondary-900 dark:text-secondary-50">
                        {log.entity} {log.entityId ? `#${log.entityId.slice(0, 8)}` : ""}
                      </TableCell>
                      <TableCell className="text-xs text-secondary-600 dark:text-secondary-400">
                        {log.userEmail || log.userId || "System / Middleware"}
                      </TableCell>
                      <TableCell className="text-xs max-w-xs truncate font-mono text-secondary-500">
                        {log.details || "-"}
                      </TableCell>
                    </TableRow>
                  ))}
                </TableBody>
              </Table>

              {/* Pagination controls */}
              <div className="flex items-center justify-between pt-4 border-t border-secondary-200 dark:border-secondary-800">
                <p className="text-xs text-secondary-500">
                  Page {page} of {totalPages}
                </p>
                <div className="flex space-x-2">
                  <Button
                    variant="outline"
                    size="sm"
                    disabled={page <= 1}
                    onClick={() => setPage((p) => Math.max(1, p - 1))}
                  >
                    Previous
                  </Button>
                  <Button
                    variant="outline"
                    size="sm"
                    disabled={page >= totalPages}
                    onClick={() => setPage((p) => Math.min(totalPages, p + 1))}
                  >
                    Next
                  </Button>
                </div>
              </div>
            </>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
